version: '3'

services:
  confax:
    build: .
    restart: always
    environment:
      - BOT_TOKEN=MzIwNjY3NDUyNTgzMzEzNDA4.XPFnfg.ICDPfmZahljiSR_8pul9V41R9uA
    volumes:
      - './guilds:/usr/share/app/guilds'
